web:
  image: node
  working_dir: /usr/src/app
  command: sh -c 'npm install; npm install -g nodemon ; nodemon -e js,jade server.js'
  links:
    - mongo
  ports:
    - "8080:8080"
  volumes:
    - ./app:/usr/src/app
mongo:
  image: mongo
